name: gaslocator
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.5
  dio: ^5.3.3
  get_it: ^7.6.4
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.2.2
  dartz: ^0.10.1
  flutter_localizations: 
    sdk: flutter
  equatable: ^2.0.5
  fluttertoast: ^8.2.2
  flutter_spinkit: ^5.2.0
  firebase_messaging: ^14.9.2
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.0
  bloc: ^8.1.3
  formz: ^0.7.0
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.1
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  google_maps_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - lang/ar.json
    - lang/en.json
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Overlock
      fonts:
        - asset: assets/fonts/Overlock-Black.ttf
          weight: 900
        - asset: assets/fonts/Overlock-Bold.ttf
          weight: 700
        - asset: assets/fonts/Overlock-Regular.ttf
          weight: 400

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
